apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-cert-admission-webhook
  namespace: istio-system
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-cert-admission-webhook
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - update
  - get
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-cert-admission-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-cert-admission-webhook
subjects:
- kind: ServiceAccount
  name: istio-cert-admission-webhook
  namespace: istio-system
